apiVersion : apps/v1
kind: Deployment
metadata:
  name: postgresdb 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb 
    spec:
      containers:
        - name: postgresdb 
          image: postgres
          ports:
            - 5432:5432
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          volumes:
            - local_postgres_data:/var/lib/postgresql/data