apiVersion: v1
kind: Service
metadata:
    annotations: 
        service.beta.kubernetes.io/azure-dns-label-name: strengthifynetapi
    name: strengthify
spec:
    type: LoadBalancer
    ports:
    - port: 5000 
    selector:
        app: strengthify

        