apiVersion: v1
kind: Service
metadata:
    annotations: 
        service.beta.kubernetes.io/azure-dns-label-name: strengthifynetapi
    name: strengthify
spec:
    type: LoadBalancer
    ports:
    - name: http
        port: 80
    - name: https
        port: 443
    selector:
        app: strengthify

        