apiVersion: v1
kind: Service
metadata:
  annotations: 
    service.beta.kubernetes.io/azure-dns-label-name: strengthifynetapi
  name: strengthify
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5001
  selector:
    app: strengthify

        